import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/Link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data)

  const [information, setInformation] = useState([...data]) //this says to just enter this data into the useState. When we call the useState, it will call the information. 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <p className={styles.description}>
          <Link href="about">About</Link>
        </p>
        <div>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            By{' '}
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              className={styles.vercelLogo}
              width={100}
              height={24}
              priority
            />
          </a>
        </div>


        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <b>Business Degrees: </b>
          {information && information.map((info, index) => {
            if (info.department === "Business") { //this filters thru the department key in the education.json file. You can add "info.department.toLowerCase()" if you want it to find upper (exact) casing or lower case is okay too.
              return (
                <Card key={index} degree={info.degree} colour="red" font="10px" /> //This is pulling the Card component, passing over the degree property
              )
            }
          })}

          <b>Computing Degrees:</b>
          {information && information.map((info, index) => {
            if (info.department === "Computing") { //this filters thru the department key in the education.json file. You can add "info.department.toLowerCase()" if you want it to find upper (exact) casing or lower case is okay too.
              return (
                <Card key={index} degree={info.degree} colour="blue" font="26px" />
                //<div key={index}>{info.degree}</div> //If not using components, this adding the key here will count the index so that the console error disappears. Each key is unique now
              )
            }
          })}
        </div>
      </main>
    </>
  )
}
