import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data)

  const [information, setInformation] = useState([...data]) //this says to just enter this data into the useState. When we call the useState, it will call the information. 

  return (
    <>
      <Head>
        <title>Creative Co.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <p className={styles.description}>
          <Link href="about" className={styles.link}>About Creative Co.</Link>
        </p>

        <div className={styles.heading}>
          <h1>Creative Co.</h1>
          <p><i>where students become leaders</i></p>
        </div>

        <div className={styles.grid}>
          <div className={styles.headerSpacing}>
            <b>Business Students</b>
          </div>
          <div className={styles.profiles}>
            {information && information.map((info, index) => {
              if (info.department === "Business") { //this filters thru the department key in the education.json file. You can add "info.department.toLowerCase()" if you want it to find upper (exact) casing or lower case is okay too.
                return (
                  <Card key={index}
                    image={info.image}
                    firstName={info.firstName}
                    degree={info.degree}
                    department={info.department}
                    gpa={info.gpa}
                    graduted={info.graduted}
                    bio={info.bio} /> //This is pulling the Card component, passing over the degree property
                )
              }
            })}
          </div>

          <div className={styles.headerSpacing}>
            <b>Computing Students</b>
          </div>
          <div className={styles.profiles}>
            {information && information.map((info, index) => {
              if (info.department === "Computing") { //this filters thru the department key in the education.json file. You can add "info.department.toLowerCase()" if you want it to find upper (exact) casing or lower case is okay too.
                return (
                  <Card key={index}
                    image={info.image}
                    firstName={info.firstName}
                    degree={info.degree}
                    departmente={info.department}
                    gpa={info.gpa}
                    graduted={info.graduted}
                    bio={info.bio} />
                  //<div key={index}>{info.degree}</div> //If not using components, this adding the key here will count the index so that the console error disappears. Each key is unique now
                )
              }
            })
            }
          </div>
        </div>
      </main>
    </>
  )
}
